export const GAME_STATUS = {
  NOT_STARTED: 'NOT_STARTED',
  ACTIVE: 'ACTIVE',
  CELEBRATION: 'CELEBRATION',
  FINALE: 'FINALE',
} as const

export type GameStatus = (typeof GAME_STATUS)[keyof typeof GAME_STATUS]

export const EFFECT_TYPES = {
  HUNT_STARTED: 'HUNT_STARTED',
  HUNT_COMPLETED: 'HUNT_COMPLETED',
  RIDDLE_SOLVED: 'RIDDLE_SOLVED',
  RIDDLE_SKIPPED: 'RIDDLE_SKIPPED',
  HINT_REQUESTED: 'HINT_REQUESTED',
  EFFECT_TRIGGERED: 'EFFECT_TRIGGERED',
  GUIDE_RESPONSE: 'GUIDE_RESPONSE',
  MANUAL_OVERRIDE: 'MANUAL_OVERRIDE',
  HELP_REQUESTED: 'HELP_REQUESTED',
  HELP_ACKNOWLEDGED: 'HELP_ACKNOWLEDGED',
  ANSWER_EVALUATED: 'ANSWER_EVALUATED',
} as const

export type EffectType = (typeof EFFECT_TYPES)[keyof typeof EFFECT_TYPES]

export const HINT_TIERS = {
  GENTLE: 'GENTLE',
  NUDGE: 'NUDGE',
  STRONG: 'STRONG',
  MANUAL: 'MANUAL',
} as const

export type HintTier = (typeof HINT_TIERS)[keyof typeof HINT_TIERS]
